<?php


namespace Commune\Chatbot\Framework\Messages;


use Commune\Chatbot\Blueprint\Message\MediaMsg;

abstract class AbsMedia extends AbsMessage implements MediaMsg
{
    public function isEmpty(): bool
    {
        return null;
    }

    public function namesAsDependency(): array
    {
        $names = parent::namesAsDependency(); // TODO: Change the autogenerated stub
        $names[] = MediaMsg::class;
        $names[] = AbsMedia::class;
        return $names;
    }

}