<?php


namespace Commune\Chatbot\Framework\Messages;


use Carbon\Carbon;
use Commune\Chatbot\Blueprint\Message\MediaMsg;

abstract class AbsMedia extends AbsMessage implements MediaMsg
{
    const MESSAGE_TYPE = MediaMsg::class;

    /**
     * @var string
     */
    protected $url = '';

    public function __construct(string $url, Carbon $createdAt = null)
    {
        $this->url = $url;
        parent::__construct($createdAt);
    }

    public function getUrl(): string
    {
        return $this->url;
    }


    public function isEmpty(): bool
    {
        return null;
    }

    public function getText(): string
    {
        return $this->toJson();
    }

    public function toMessageData(): array
    {
        return [
            'src' => $this->url
        ];
    }


    public function namesAsDependency(): array
    {
        $names = parent::namesAsDependency(); // TODO: Change the autogenerated stub
        $names[] = MediaMsg::class;
        $names[] = AbsMedia::class;
        return $names;
    }

}