<?php


namespace Commune\Support\OptionRepo\Storage\Yaml;


use Commune\Support\OptionRepo\Storage\FileStorageMeta;

/**
 * @mixin  FileStorageMeta
 * @property-read int $inline yaml 序列化时, 第几层会压缩成单行
 * @property-read int $intent 每次缩进的长度.
 */
class YamlStorageMeta extends FileStorageMeta
{
    const DRIVER = YamlRootStorage::class;


    public static function stub(): array
    {
        $data = parent::stub(); // TODO: Change the autogenerated stub
        $data['inline'] = 6;
        $data['intent'] = 2;
        return $data;
    }
}