<?php


namespace Commune\Chatbot\OOHost\Directing\Redirects;


use Commune\Chatbot\OOHost\Context\Context;
use Commune\Chatbot\OOHost\Dialogue\Dialog;
use Commune\Chatbot\OOHost\Directing\AbsNavigator;
use Commune\Chatbot\OOHost\Directing\Navigator;
use Commune\Chatbot\OOHost\Directing\Stage\GoStage;
use Commune\Chatbot\OOHost\History\History;

abstract class Redirector extends AbsNavigator
{

    /**
     * @var Context
     */
    protected $to;

    /**
     * @var string|null
     */
    protected $resetStage;

    /**
     * Redirector constructor.
     * @param Dialog $dialog
     * @param History $history
     * @param Context $to
     * @param string|null $stage
     */
    public function __construct(
        Dialog $dialog,
        History $history,
        Context $to,
        string $stage = null
    )
    {
        $this->to = $to;
        $this->resetStage = $stage;
        parent::__construct($dialog, $history);
    }

    public function startCurrent(): Navigator
    {
        if (isset($this->resetStage)) {
            return new GoStage(
                $this->dialog,
                $this->history,
                $this->resetStage,
                true
            );
        }
        return parent::startCurrent(); // TODO: Change the autogenerated stub
    }
}